// Emoji Word Map for Emoji Speak Transform
// Maps emojis to arrays of related keywords
// When a word is typed, a random emoji from matching entries is returned

window.emojiKeywords = {
    // Emotions & Feelings - Happy
    '😊': ['happy', 'smile', 'pleased', 'content', 'glad'],
    '😁': ['grin', 'smile', 'happy', 'excited', 'beaming', 'haha', 'ha', 'hehe'],
    '😂': ['laugh', 'lol', 'crying', 'tears', 'funny', 'hilarious', 'haha', 'ha', 'hehe'],
    '🤣': ['laugh', 'rofl', 'lol', 'rolling', 'hilarious', 'haha', 'ha', 'hehe'],
    '😄': ['happy', 'smile', 'joy', 'cheerful', 'haha', 'ha', 'hehe'],
    '😃': ['happy', 'smile', 'excited', 'haha', 'ha', 'hehe'],
    '🤩': ['excited', 'starstruck', 'wow', 'amazing'],
    '😍': ['love', 'heart', 'adore', 'crush'],
    '🥰': ['love', 'hearts', 'affection', 'sweet'],
    '😘': ['kiss', 'love', 'smooch', 'mwah'],
    '😉': ['wink', 'flirt', 'playful'],
    
    // Emotions - Sad & Negative
    '😢': ['sad', 'cry', 'tear', 'upset'],
    '😭': ['cry', 'sobbing', 'bawling', 'sad', 'tears'],
    '😔': ['sad', 'pensive', 'down', 'disappointed'],
    '😞': ['sad', 'disappointed', 'upset', 'lose'],
    '😟': ['worried', 'anxious', 'concerned'],
    '😕': ['confused', 'uncertain', 'puzzled'],
    '🤔': ['think', 'thinking', 'hmm', 'wonder', 'ponder'],
    '😐': ['neutral', 'meh', 'blank', 'expressionless'],
    
    // Emotions - Angry
    '😡': ['angry', 'mad', 'furious', 'rage', 'pissed'],
    '😠': ['angry', 'mad', 'annoyed', 'grumpy'],
    '🤬': ['angry', 'cursing', 'swearing', 'rage'],
    
    // Emotions - Surprised & Shocked
    '😮': ['wow', 'surprised', 'shocked', 'amazed'],
    '😲': ['shocked', 'surprised', 'astonished'],
    '😱': ['scared', 'shock', 'screaming', 'fear', 'terrified'],
    '😨': ['scared', 'fearful', 'afraid', 'anxious'],
    
    // Emotions - Other
    '😎': ['cool', 'sunglasses', 'smooth', 'slick'],
    '😴': ['sleep', 'sleeping', 'tired', 'sleepy', 'zzz'],
    '🥱': ['tired', 'sleepy', 'bored', 'yawn'],
    '😰': ['nervous', 'anxious', 'sweat', 'worried'],
    '😅': ['sweat', 'relief', 'phew', 'nervous'],
    '🤢': ['sick', 'nauseous', 'ill', 'gross'],
    '🤮': ['sick', 'vomit', 'puke', 'ill'],
    '😇': ['angel', 'innocent', 'halo', 'saint'],
    '😈': ['devil', 'evil', 'mischief', 'naughty'],
    '💀': ['dead', 'skull', 'death', 'dying'],
    '👻': ['ghost', 'boo', 'spooky', 'phantom'],
    '🎉': ['party', 'celebrate', 'celebration', 'hooray', 'festive'],
    '🎊': ['party', 'celebrate', 'confetti', 'celebration'],
    
    // Animals - Pets & Common
    '🐕': ['dog', 'puppy', 'pet', 'canine', 'pup'],
    '🐶': ['dog', 'puppy', 'doggy', 'pet', 'pup'],
    '🦮': ['dog', 'guide', 'service'],
    '🐕‍🦺': ['dog', 'service'],
    '🐩': ['dog', 'poodle', 'puppy'],
    '🐱': ['cat', 'kitty', 'kitten', 'pet', 'feline'],
    '🐈': ['cat', 'kitty', 'feline', 'pet'],
    '🐈‍⬛': ['cat', 'black'],
    '🐭': ['mouse', 'mice', 'rodent'],
    '🐹': ['hamster', 'pet', 'rodent'],
    '🐰': ['rabbit', 'bunny', 'easter', 'hare'],
    '🐇': ['rabbit', 'bunny', 'hare'],
    
    // Animals - Wild
    '🦊': ['fox', 'foxy', 'sly'],
    '🐻': ['bear', 'teddy'],
    '🐼': ['panda', 'bear'],
    '🐨': ['koala', 'bear', 'australian'],
    '🐯': ['tiger', 'fierce', 'striped'],
    '🦁': ['lion', 'king', 'mane', 'roar'],
    '🐮': ['cow', 'cattle', 'moo'],
    '🐷': ['pig', 'piggy', 'oink', 'swine'],
    '🐸': ['frog', 'toad', 'ribbit'],
    '🐵': ['monkey', 'primate', 'ape'],
    '🐒': ['monkey', 'primate'],
    '🦍': ['gorilla', 'ape', 'kong'],
    '🦧': ['orangutan', 'ape'],
    '🐺': ['wolf', 'howl', 'pack'],
    '🦝': ['raccoon', 'trash'],
    '🐴': ['horse', 'pony', 'stallion', 'mare'],
    '🦄': ['unicorn', 'magical', 'fantasy', 'rainbow'],
    '🦓': ['zebra', 'striped', 'stripes'],
    '🦌': ['deer', 'reindeer', 'stag', 'doe'],
    '🐘': ['elephant', 'trunk', 'big', 'large'],
    '🦏': ['rhino', 'rhinoceros', 'horn'],
    '🦛': ['hippo', 'hippopotamus'],
    '🦒': ['giraffe', 'tall', 'neck'],
    
    // Animals - Birds
    '🐔': ['chicken', 'rooster', 'hen', 'poultry'],
    '🐓': ['rooster', 'chicken', 'cock'],
    '🐣': ['chick', 'baby', 'hatching', 'bird'],
    '🐤': ['chick', 'baby', 'bird'],
    '🐥': ['chick', 'duckling', 'baby', 'bird'],
    '🐦': ['bird', 'birdie', 'tweet'],
    '🐧': ['penguin', 'antarctic', 'bird'],
    '🦆': ['duck', 'quack', 'waterfowl'],
    '🦅': ['eagle', 'bird', 'freedom', 'america'],
    '🦉': ['owl', 'wise', 'hoot', 'night'],
    '🦇': ['bat', 'vampire', 'night', 'flying'],
    '🦜': ['parrot', 'bird', 'tropical', 'colorful'],
    '🦚': ['peacock', 'bird', 'fancy', 'colorful'],
    
    // Animals - Insects & Small
    '🐝': ['bee', 'buzz', 'honey', 'bumblebee'],
    '🐛': ['bug', 'caterpillar', 'worm', 'insect'],
    '🦋': ['butterfly', 'beautiful', 'insect', 'flying'],
    '🐌': ['snail', 'slow', 'shell'],
    '🐞': ['ladybug', 'bug', 'insect', 'beetle'],
    '🐜': ['ant', 'insect', 'small', 'tiny'],
    '🕷️': ['spider', 'web', 'arachnid', 'creepy'],
    '🦂': ['scorpion', 'sting', 'desert'],
    '🦟': ['mosquito', 'bug', 'bite', 'annoying'],
    
    // Animals - Marine
    '🐍': ['snake', 'serpent', 'slither', 'reptile'],
    '🦎': ['lizard', 'reptile', 'gecko'],
    '🐊': ['alligator', 'crocodile', 'reptile'],
    '🐢': ['turtle', 'tortoise', 'slow', 'shell'],
    '🐉': ['dragon', 'fantasy', 'mythical', 'fire'],
    '🐲': ['dragon', 'fantasy', 'mythical'],
    '🐟': ['fish', 'seafood', 'swimming'],
    '🐠': ['fish', 'tropical', 'colorful'],
    '🐡': ['fish', 'puffer', 'blowfish'],
    '🦈': ['shark', 'jaws', 'ocean', 'dangerous'],
    '🐋': ['whale', 'ocean', 'big', 'huge'],
    '🐬': ['dolphin', 'ocean', 'smart', 'friendly'],
    '🐙': ['octopus', 'tentacles', 'ocean', 'squid'],
    '🦑': ['squid', 'octopus', 'ocean', 'tentacles'],
    '🦀': ['crab', 'ocean', 'seafood', 'crustacean'],
    '🦞': ['lobster', 'seafood', 'ocean', 'crustacean'],
    '🦐': ['shrimp', 'prawn', 'seafood', 'ocean'],
    '🦪': ['oyster', 'seafood', 'pearl', 'shell'],
    
    // Food - Fast Food & Main
    '🍕': ['pizza', 'slice', 'cheese', 'pepperoni', 'italian'],
    '🍔': ['burger', 'hamburger', 'cheeseburger', 'food'],
    '🍟': ['fries', 'chips', 'potato', 'french'],
    '🌭': ['hotdog', 'dog', 'sausage', 'frank'],
    '🌮': ['taco', 'mexican', 'shell'],
    '🌯': ['burrito', 'mexican', 'wrap'],
    '🥙': ['wrap', 'pita', 'gyro', 'sandwich'],
    '🥪': ['sandwich', 'sub', 'lunch'],
    '🥗': ['salad', 'healthy', 'greens', 'vegetables'],
    '🍝': ['pasta', 'spaghetti', 'italian', 'noodles'],
    '🍜': ['ramen', 'noodles', 'soup', 'asian'],
    '🍲': ['stew', 'soup', 'pot', 'food'],
    '🍛': ['curry', 'rice', 'indian', 'spicy'],
    '🍣': ['sushi', 'japanese', 'fish', 'raw'],
    '🍱': ['bento', 'lunch', 'japanese', 'box'],
    '🥘': ['paella', 'food', 'dish', 'pan'],
    
    // Food - Meat & Protein
    '🍖': ['meat', 'bone', 'food', 'leg'],
    '🍗': ['chicken', 'drumstick', 'meat', 'poultry'],
    '🥩': ['steak', 'meat', 'beef', 'red'],
    '🥓': ['bacon', 'meat', 'breakfast', 'pork'],
    '🥚': ['egg', 'breakfast', 'protein'],
    '🍳': ['cooking', 'egg', 'frying', 'breakfast'],
    
    // Food - Bread & Baked
    '🍞': ['bread', 'loaf', 'toast', 'baked'],
    '🥐': ['croissant', 'bread', 'french', 'pastry'],
    '🥖': ['baguette', 'bread', 'french'],
    '🥨': ['pretzel', 'snack', 'twisted'],
    '🧀': ['cheese', 'dairy', 'yellow'],
    
    // Food - Fruits
    '🍎': ['apple', 'fruit', 'red', 'healthy'],
    '🍏': ['apple', 'fruit', 'green', 'granny'],
    '🍊': ['orange', 'fruit', 'citrus', 'vitamin'],
    '🍋': ['lemon', 'citrus', 'sour', 'yellow'],
    '🍌': ['banana', 'fruit', 'yellow', 'potassium'],
    '🍉': ['watermelon', 'fruit', 'summer', 'juicy'],
    '🍇': ['grapes', 'fruit', 'wine', 'purple'],
    '🍓': ['strawberry', 'berry', 'fruit', 'red'],
    '🫐': ['blueberry', 'berry', 'fruit', 'blue'],
    '🍈': ['melon', 'fruit', 'cantaloupe'],
    '🍒': ['cherry', 'fruit', 'red', 'cherries'],
    '🍑': ['peach', 'fruit', 'fuzzy', 'juicy'],
    '🥭': ['mango', 'fruit', 'tropical', 'juicy'],
    '🍍': ['pineapple', 'fruit', 'tropical', 'spiky'],
    '🥥': ['coconut', 'tropical', 'palm', 'fruit'],
    '🥝': ['kiwi', 'fruit', 'green', 'fuzzy'],
    '🥑': ['avocado', 'fruit', 'green', 'healthy', 'guac'],
    
    // Food - Vegetables
    '🍅': ['tomato', 'vegetable', 'red', 'fruit'],
    '🥔': ['potato', 'vegetable', 'spud', 'tater'],
    '🥕': ['carrot', 'vegetable', 'orange', 'healthy'],
    '🌽': ['corn', 'vegetable', 'yellow', 'maize'],
    '🌶️': ['pepper', 'chili', 'hot', 'spicy', 'jalapeno'],
    '🫑': ['pepper', 'bell', 'vegetable', 'capsicum'],
    '🥒': ['cucumber', 'vegetable', 'green', 'pickle'],
    '🥬': ['lettuce', 'vegetable', 'green', 'leafy', 'cabbage'],
    '🥦': ['broccoli', 'vegetable', 'green', 'healthy'],
    '🧄': ['garlic', 'vegetable', 'flavor', 'bulb'],
    '🧅': ['onion', 'vegetable', 'layers', 'cry'],
    '🍄': ['mushroom', 'fungus', 'shroom', 'toadstool'],
    
    // Food - Desserts & Sweets
    '🍰': ['cake', 'dessert', 'birthday', 'sweet', 'slice'],
    '🎂': ['cake', 'birthday', 'celebration', 'candles'],
    '🧁': ['cupcake', 'cake', 'dessert', 'sweet'],
    '🥧': ['pie', 'dessert', 'baked', 'slice'],
    '🍪': ['cookie', 'biscuit', 'dessert', 'sweet', 'chocolate'],
    '🍩': ['donut', 'doughnut', 'dessert', 'sweet', 'fried'],
    '🍫': ['chocolate', 'candy', 'sweet', 'cocoa', 'bar'],
    '🍬': ['candy', 'sweet', 'sugar', 'wrapper'],
    '🍭': ['lollipop', 'candy', 'sweet', 'sucker'],
    '🍮': ['custard', 'pudding', 'dessert', 'sweet', 'flan'],
    '🍯': ['honey', 'sweet', 'bee', 'golden'],
    '🍦': ['icecream', 'ice', 'cream', 'dessert', 'cold', 'cone'],
    '🍧': ['shaved', 'ice', 'dessert', 'cold', 'snow'],
    '🍨': ['icecream', 'ice', 'cream', 'dessert', 'bowl'],
    
    // Drinks
    '☕': ['coffee', 'cafe', 'espresso', 'latte', 'hot', 'java'],
    '🍵': ['tea', 'green', 'hot', 'cup', 'matcha'],
    '🧃': ['juice', 'box', 'drink', 'kid'],
    '🥤': ['soda', 'pop', 'drink', 'cup', 'straw'],
    '🧋': ['bubble', 'tea', 'boba', 'drink', 'tapioca'],
    '🥛': ['milk', 'dairy', 'drink', 'white'],
    '🍼': ['bottle', 'baby', 'milk', 'feeding'],
    '🍺': ['beer', 'ale', 'alcohol', 'drink', 'brew', 'cheers'],
    '🍻': ['beer', 'cheers', 'drinks', 'celebration', 'toast'],
    '🍷': ['wine', 'alcohol', 'drink', 'red', 'glass'],
    '🥂': ['champagne', 'celebrate', 'toast', 'cheers', 'sparkling'],
    '🍸': ['cocktail', 'martini', 'drink', 'alcohol'],
    '🍹': ['cocktail', 'tropical', 'drink', 'vacation'],
    '🧊': ['ice', 'cold', 'cube', 'frozen'],
    '💧': ['water', 'drop', 'liquid', 'droplet'],
    
    // Body & Gestures
    '👋': ['wave', 'hello', 'hi', 'bye', 'hand'],
    '🤚': ['hand', 'raised', 'stop', 'palm'],
    '🖐️': ['hand', 'fingers', 'five', 'palm'],
    '✋': ['hand', 'stop', 'raised', 'palm'],
    '🖖': ['vulcan', 'spock', 'hand', 'star', 'trek'],
    '👌': ['ok', 'okay', 'good', 'perfect', 'fine'],
    '🤌': ['fingers', 'italian', 'pinch', 'hand'],
    '🤏': ['pinch', 'small', 'tiny', 'little'],
    '✌️': ['peace', 'victory', 'two', 'fingers'],
    '🤞': ['fingers', 'crossed', 'luck', 'hope'],
    '🤟': ['love', 'sign', 'rock', 'hand'],
    '🤘': ['rock', 'metal', 'horns', 'devil'],
    '🤙': ['call', 'phone', 'hang', 'shaka'],
    '👈': ['point', 'left', 'finger', 'direction'],
    '👉': ['point', 'right', 'finger', 'direction'],
    '👆': ['point', 'up', 'finger', 'direction'],
    '👇': ['point', 'down', 'finger', 'direction'],
    '☝️': ['point', 'up', 'one', 'finger'],
    '👍': ['thumbsup', 'good', 'yes', 'like', 'approve', 'up'],
    '👎': ['thumbsdown', 'bad', 'no', 'dislike', 'disapprove', 'down'],
    '✊': ['fist', 'power', 'strength', 'solidarity'],
    '👊': ['fist', 'punch', 'bump', 'fight'],
    '🤛': ['fist', 'punch', 'left', 'bump'],
    '🤜': ['fist', 'punch', 'right', 'bump'],
    '👏': ['clap', 'applause', 'hands', 'bravo', 'praise'],
    '🙌': ['hands', 'raised', 'celebration', 'praise', 'hooray'],
    '👐': ['hands', 'open', 'hug'],
    '🤲': ['hands', 'palms', 'prayer', 'offering'],
    '🤝': ['handshake', 'deal', 'agreement', 'shake'],
    '🙏': ['pray', 'prayer', 'please', 'thank', 'namaste', 'hands'],
    '💪': ['muscle', 'strong', 'strength', 'flex', 'arm', 'power'],
    '🦵': ['leg', 'kick', 'limb'],
    '🦶': ['foot', 'feet', 'toe'],
    '👀': ['eyes', 'looking', 'watching', 'see'],
    '👁️': ['eye', 'see', 'look', 'watch'],
    '👃': ['nose', 'smell', 'sniff'],
    '👂': ['ear', 'hear', 'listen'],
    '🧠': ['brain', 'smart', 'think', 'intelligent'],
    '🦴': ['bone', 'skeleton', 'anatomy'],
    '🦷': ['teeth', 'tooth', 'dental', 'dentist'],
    '👅': ['tongue', 'taste', 'lick'],
    '👄': ['mouth', 'lips', 'kiss'],
    
    // People & Professions
    '👨': ['man', 'male', 'guy', 'adult'],
    '👩': ['woman', 'female', 'lady', 'adult'],
    '👦': ['boy', 'male', 'child', 'kid'],
    '👧': ['girl', 'female', 'child', 'kid'],
    '👶': ['baby', 'infant', 'newborn', 'child'],
    '🧒': ['child', 'kid', 'young'],
    '👨‍⚕️': ['doctor', 'physician', 'medical', 'health'],
    '👩‍⚕️': ['doctor', 'nurse', 'medical', 'health'],
    '👨‍🎓': ['student', 'graduate', 'scholar', 'education'],
    '👨‍🏫': ['teacher', 'professor', 'educator', 'instructor'],
    '👨‍💻': ['programmer', 'developer', 'coder', 'engineer', 'tech'],
    '👨‍🔬': ['scientist', 'researcher', 'lab', 'chemistry'],
    '👨‍🎨': ['artist', 'painter', 'creative'],
    '👨‍🍳': ['chef', 'cook', 'culinary'],
    '👨‍🎤': ['singer', 'musician', 'rockstar', 'performer'],
    '👨‍✈️': ['pilot', 'captain', 'aviator', 'flying'],
    '👨‍🚀': ['astronaut', 'space', 'cosmonaut'],
    '👨‍🚒': ['firefighter', 'fireman', 'rescue'],
    '👮': ['police', 'cop', 'officer', 'law'],
    '🕵️': ['detective', 'spy', 'investigator', 'sleuth'],
    '💂': ['guard', 'soldier', 'sentry'],
    '🥷': ['ninja', 'stealth', 'martial', 'warrior'],
    '👷': ['construction', 'worker', 'builder', 'hardhat'],
    '🤴': ['prince', 'royal', 'king'],
    '👸': ['princess', 'royal', 'queen'],
    '👑': ['crown', 'king', 'queen', 'royal', 'royalty'],
    '🧙': ['wizard', 'magic', 'sorcerer', 'merlin'],
    '🧚': ['fairy', 'magical', 'wings', 'pixie'],
    '🧛': ['vampire', 'dracula', 'blood', 'fangs'],
    '🧜': ['mermaid', 'ocean', 'sea', 'mythical'],
    '🧝': ['elf', 'fantasy', 'magical', 'pointed'],
    '🧞': ['genie', 'wish', 'lamp', 'magical'],
    '🧟': ['zombie', 'undead', 'walking', 'dead'],
    '🦸': ['superhero', 'hero', 'super', 'powers'],
    '🦹': ['villain', 'evil', 'bad', 'super'],
    '🤶': ['mrs', 'claus', 'christmas', 'santa'],
    '🎅': ['santa', 'christmas', 'claus', 'father'],
    '👼': ['angel', 'cherub', 'heaven', 'halo'],
    '💏': ['kiss', 'couple', 'romance', 'love'],
    '💑': ['couple', 'love', 'romance', 'heart'],
    '👪': ['family', 'parents', 'kids', 'home'],
    '🤗': ['hug', 'hugging', 'embrace', 'cuddle'],
    '🤳': ['selfie', 'photo', 'camera', 'phone'],
    
    // Activities & Sports
    '⚽': ['soccer', 'football', 'ball', 'sport'],
    '🏀': ['basketball', 'ball', 'sport', 'hoops'],
    '🏈': ['football', 'american', 'ball', 'sport'],
    '⚾': ['baseball', 'ball', 'sport', 'diamond'],
    '🎾': ['tennis', 'ball', 'sport', 'racket'],
    '🏐': ['volleyball', 'ball', 'sport', 'beach'],
    '🏉': ['rugby', 'football', 'ball', 'sport'],
    '🎱': ['billiards', 'pool', 'eight', 'ball'],
    '🏓': ['pingpong', 'tabletennis', 'paddle', 'sport'],
    '🏸': ['badminton', 'shuttlecock', 'sport'],
    '🥊': ['boxing', 'glove', 'fight', 'punch'],
    '🥋': ['martial', 'arts', 'karate', 'judo', 'gi'],
    '⛳': ['golf', 'hole', 'sport', 'flag'],
    '🏹': ['archery', 'bow', 'arrow', 'target'],
    '🎯': ['target', 'bullseye', 'darts', 'aim'],
    '🏃': ['run', 'running', 'jog', 'exercise', 'sprint'],
    '🚶': ['walk', 'walking', 'stroll', 'pedestrian'],
    '💃': ['dance', 'dancing', 'salsa', 'party'],
    '🕺': ['dance', 'dancing', 'disco', 'party'],
    '🤸': ['gymnastics', 'flip', 'cartwheel', 'jump'],
    '🏊': ['swim', 'swimming', 'pool', 'water'],
    '🏄': ['surf', 'surfing', 'wave', 'beach'],
    '🚴': ['bike', 'cycling', 'bicycle', 'ride'],
    '🏋️': ['lift', 'lifting', 'weights', 'gym', 'workout'],
    '🤼': ['wrestle', 'wrestling', 'fight', 'grapple'],
    '🤺': ['fencing', 'sword', 'duel', 'sport'],
    '⛷️': ['ski', 'skiing', 'snow', 'sport'],
    '🏂': ['snowboard', 'snow', 'sport', 'winter'],
    '🧗': ['climb', 'climbing', 'rock', 'mountain'],
    '🧘': ['yoga', 'meditate', 'meditation', 'zen', 'peace', 'calm'],
    '🎮': ['game', 'gaming', 'videogame', 'play', 'controller'],
    '🎲': ['dice', 'game', 'roll', 'random'],
    '♠️': ['spade', 'card', 'suit', 'black'],
    '♥️': ['heart', 'card', 'suit', 'love', 'red'],
    '♦️': ['diamond', 'card', 'suit', 'red'],
    '♣️': ['club', 'card', 'suit', 'black'],
    '🎨': ['art', 'paint', 'painting', 'artist', 'creative', 'palette'],
    '🎭': ['theater', 'drama', 'masks', 'acting', 'performance'],
    '🎪': ['circus', 'tent', 'carnival', 'show'],
    '🎬': ['movie', 'film', 'cinema', 'action', 'clapper'],
    '🎤': ['microphone', 'sing', 'singing', 'karaoke', 'mic'],
    '🎧': ['headphones', 'music', 'audio', 'listen'],
    '🎵': ['music', 'note', 'musical', 'song'],
    '🎶': ['music', 'notes', 'musical', 'song', 'melody'],
    '🎸': ['guitar', 'rock', 'music', 'instrument'],
    '🎹': ['piano', 'keyboard', 'music', 'instrument'],
    '🎺': ['trumpet', 'music', 'instrument', 'brass'],
    '🎻': ['violin', 'music', 'instrument', 'strings'],
    '🥁': ['drum', 'drums', 'music', 'instrument'],
    '📚': ['books', 'library', 'study', 'read', 'reading', 'education'],
    '📖': ['book', 'read', 'reading', 'novel', 'open'],
    '✍️': ['write', 'writing', 'pen', 'author'],
    '📝': ['note', 'memo', 'write', 'paper'],
    
    // Objects & Technology
    '📱': ['phone', 'mobile', 'cell', 'smartphone', 'iphone'],
    '☎️': ['telephone', 'phone', 'call', 'landline'],
    '📞': ['telephone', 'phone', 'receiver', 'call'],
    '💻': ['computer', 'laptop', 'pc', 'mac', 'work'],
    '⌨️': ['keyboard', 'typing', 'computer', 'keys'],
    '🖱️': ['mouse', 'computer', 'click', 'pointer'],
    '🖥️': ['computer', 'desktop', 'monitor', 'screen'],
    '🖨️': ['printer', 'print', 'copy', 'office'],
    '📷': ['camera', 'photo', 'picture', 'photography'],
    '📸': ['camera', 'photo', 'flash', 'picture'],
    '📹': ['video', 'camera', 'recording', 'film'],
    '🎥': ['movie', 'camera', 'film', 'cinema'],
    '📺': ['tv', 'television', 'screen', 'watch'],
    '📻': ['radio', 'music', 'broadcast', 'fm'],
    '⏰': ['alarm', 'clock', 'time', 'wake'],
    '⏱️': ['stopwatch', 'timer', 'time', 'clock'],
    '⏲️': ['timer', 'clock', 'countdown'],
    '🕐': ['clock', 'one', 'time', 'hour'],
    '⌚': ['watch', 'time', 'clock', 'wrist'],
    '📡': ['satellite', 'antenna', 'dish', 'signal'],
    '🛰️': ['satellite', 'space', 'orbit', 'gps'],
    '🔋': ['battery', 'power', 'energy', 'charge'],
    '🔌': ['plug', 'electric', 'power', 'outlet'],
    '💡': ['lightbulb', 'light', 'idea', 'bright', 'bulb'],
    '🔦': ['flashlight', 'torch', 'light', 'beam'],
    '🕯️': ['candle', 'light', 'flame', 'wax'],
    
    // Tools & Weapons
    '🔨': ['hammer', 'tool', 'nail', 'build'],
    '🪛': ['screwdriver', 'tool', 'screw', 'fix'],
    '🔧': ['wrench', 'tool', 'mechanic', 'spanner'],
    '🪚': ['saw', 'tool', 'cut', 'wood'],
    '⚙️': ['gear', 'cog', 'settings', 'mechanical'],
    '🔩': ['bolt', 'nut', 'screw', 'fastener'],
    '🪓': ['axe', 'chop', 'wood', 'tool'],
    '⚒️': ['hammer', 'pick', 'tool', 'mine'],
    '🛠️': ['tools', 'hammer', 'wrench', 'repair'],
    '🗡️': ['sword', 'blade', 'weapon', 'dagger'],
    '⚔️': ['swords', 'crossed', 'battle', 'fight', 'weapon'],
    '🔪': ['knife', 'blade', 'cut', 'sharp'],
    '🏹': ['bow', 'arrow', 'weapon', 'archery'],
    '🛡️': ['shield', 'protection', 'defend', 'guard'],
    '💣': ['bomb', 'explosive', 'danger', 'blast'],
    '🔫': ['gun', 'pistol', 'weapon', 'shoot'],
    
    // Money & Value
    '💰': ['money', 'bag', 'cash', 'rich', 'dollar', 'wealth'],
    '💵': ['dollar', 'money', 'bill', 'cash', 'hundred'],
    '💴': ['yen', 'money', 'japan', 'currency'],
    '💶': ['euro', 'money', 'europe', 'currency'],
    '💷': ['pound', 'money', 'british', 'currency'],
    '💸': ['money', 'flying', 'cash', 'spend', 'expense'],
    '💳': ['card', 'credit', 'debit', 'payment'],
    '💎': ['diamond', 'gem', 'jewel', 'precious', 'valuable'],
    '👑': ['crown', 'royal', 'king', 'queen'],
    '💍': ['ring', 'diamond', 'wedding', 'engagement', 'jewelry'],
    '🏆': ['trophy', 'award', 'win', 'champion', 'prize', 'first'],
    '🥇': ['gold', 'medal', 'first', 'win', 'champion'],
    '🥈': ['silver', 'medal', 'second', 'place'],
    '🥉': ['bronze', 'medal', 'third', 'place'],
    '🏅': ['medal', 'award', 'gold', 'achievement'],
    
    // Office & School
    '✏️': ['pencil', 'write', 'draw', 'school'],
    '✒️': ['pen', 'write', 'ink', 'fountain'],
    '🖊️': ['pen', 'write', 'ballpoint'],
    '🖋️': ['pen', 'fountain', 'write', 'ink'],
    '📏': ['ruler', 'measure', 'straight', 'school'],
    '📐': ['triangle', 'ruler', 'geometry', 'school'],
    '✂️': ['scissors', 'cut', 'snip', 'craft'],
    '📌': ['pin', 'pushpin', 'tack', 'attach'],
    '📍': ['pin', 'location', 'map', 'place'],
    '🖇️': ['paperclip', 'clip', 'attach', 'office'],
    '📎': ['paperclip', 'clip', 'attach', 'office'],
    '📄': ['paper', 'document', 'page', 'file'],
    '📃': ['paper', 'page', 'curl', 'document'],
    '📋': ['clipboard', 'paper', 'document', 'list'],
    '📁': ['folder', 'file', 'directory', 'organize'],
    '📂': ['folder', 'open', 'file', 'directory'],
    '🗂️': ['dividers', 'index', 'tabs', 'organize'],
    '📰': ['newspaper', 'news', 'article', 'press'],
    '📜': ['scroll', 'paper', 'ancient', 'document'],
    '📦': ['box', 'package', 'parcel', 'shipping', 'delivery'],
    '✉️': ['envelope', 'mail', 'letter', 'message'],
    '📧': ['email', 'mail', 'message', 'inbox'],
    '📮': ['mailbox', 'post', 'mail', 'letter'],
    '🎁': ['gift', 'present', 'box', 'wrapped', 'surprise'],
    '🎀': ['ribbon', 'bow', 'gift', 'pretty'],
    '🎈': ['balloon', 'party', 'celebration', 'float'],
    
    // Transportation - Cars
    '🚗': ['car', 'auto', 'vehicle', 'drive', 'automobile'],
    '🚕': ['taxi', 'cab', 'ride', 'yellow'],
    '🚙': ['suv', 'car', 'vehicle', 'truck'],
    '🏎️': ['racecar', 'fast', 'racing', 'formula'],
    '🚓': ['police', 'cop', 'car', 'patrol'],
    '🚑': ['ambulance', 'emergency', 'medical', 'hospital'],
    '🚒': ['firetruck', 'fire', 'emergency', 'truck'],
    '🚚': ['truck', 'delivery', 'moving', 'lorry'],
    '🚛': ['truck', 'semi', 'lorry', 'trailer'],
    '🚐': ['van', 'minibus', 'vehicle'],
    '🚌': ['bus', 'coach', 'transit', 'public'],
    
    // Transportation - Other
    '🚲': ['bike', 'bicycle', 'cycle', 'pedal'],
    '🏍️': ['motorcycle', 'bike', 'motorbike', 'chopper'],
    '🛵': ['scooter', 'moped', 'vespa'],
    '🛴': ['scooter', 'kick', 'ride'],
    '✈️': ['airplane', 'plane', 'flight', 'fly', 'jet'],
    '🛩️': ['plane', 'small', 'aircraft'],
    '🚁': ['helicopter', 'chopper', 'heli', 'copter'],
    '🚂': ['train', 'locomotive', 'steam', 'railway'],
    '🚃': ['train', 'railway', 'car', 'tram'],
    '🚄': ['train', 'highspeed', 'bullet', 'fast'],
    '🚅': ['train', 'bullet', 'fast', 'shinkansen'],
    '🚆': ['train', 'railway', 'metro'],
    '🚇': ['subway', 'metro', 'underground', 'tube'],
    '🚈': ['train', 'light', 'rail', 'tram'],
    '🚉': ['station', 'train', 'railway', 'metro'],
    '🚊': ['tram', 'trolley', 'streetcar'],
    '🚝': ['monorail', 'train', 'elevated'],
    '⛵': ['sailboat', 'boat', 'sail', 'yacht'],
    '🚤': ['speedboat', 'boat', 'fast', 'motor'],
    '🛥️': ['boat', 'motor', 'yacht', 'ship'],
    '🛳️': ['ship', 'cruise', 'passenger', 'boat'],
    '⛴️': ['ferry', 'boat', 'ship', 'passenger'],
    '🚢': ['ship', 'boat', 'cruise', 'vessel'],
    '⚓': ['anchor', 'ship', 'boat', 'navy'],
    '🚀': ['rocket', 'space', 'launch', 'nasa', 'shuttle'],
    '🛸': ['ufo', 'alien', 'flying', 'saucer', 'spaceship'],
    
    // Nature & Weather
    '☀️': ['sun', 'sunny', 'bright', 'day', 'sunshine'],
    '🌞': ['sun', 'face', 'sunny', 'bright'],
    '⭐': ['star', 'bright', 'shine', 'sparkle'],
    '🌟': ['star', 'glowing', 'shine', 'sparkle', 'shiny'],
    '✨': ['sparkles', 'stars', 'shine', 'magic', 'magical', 'twinkle'],
    '💫': ['dizzy', 'star', 'sparkle', 'shine'],
    '🌙': ['moon', 'crescent', 'night', 'lunar'],
    '🌚': ['moon', 'new', 'dark', 'face'],
    '🌛': ['moon', 'quarter', 'face'],
    '🌜': ['moon', 'quarter', 'face'],
    '🌝': ['moon', 'full', 'face'],
    '☁️': ['cloud', 'cloudy', 'weather', 'sky'],
    '⛅': ['cloud', 'sun', 'partly', 'weather'],
    '⛈️': ['storm', 'thunder', 'lightning', 'cloud', 'weather'],
    '🌤️': ['sun', 'cloud', 'partly', 'weather'],
    '🌥️': ['cloud', 'sun', 'behind', 'weather'],
    '🌦️': ['sun', 'rain', 'weather', 'cloud'],
    '🌧️': ['rain', 'rainy', 'weather', 'cloud', 'wet'],
    '🌨️': ['snow', 'snowing', 'weather', 'cloud', 'cold'],
    '🌩️': ['cloud', 'lightning', 'storm', 'weather'],
    '🌪️': ['tornado', 'cyclone', 'twister', 'wind', 'storm'],
    '🌫️': ['fog', 'foggy', 'misty', 'weather'],
    '🌬️': ['wind', 'blow', 'windy', 'weather'],
    '💨': ['wind', 'blow', 'dash', 'fast', 'air'],
    '🌀': ['cyclone', 'hurricane', 'typhoon', 'spiral'],
    '🌈': ['rainbow', 'colorful', 'colors', 'pride', 'weather'],
    '☂️': ['umbrella', 'rain', 'protect', 'weather'],
    '⛱️': ['umbrella', 'beach', 'sun', 'shade'],
    '⚡': ['lightning', 'bolt', 'electric', 'fast', 'zap', 'thunder'],
    '❄️': ['snowflake', 'snow', 'cold', 'winter', 'frozen'],
    '☃️': ['snowman', 'snow', 'winter', 'cold'],
    '⛄': ['snowman', 'snow', 'winter', 'frosty'],
    '☄️': ['comet', 'meteor', 'space', 'shooting'],
    '🔥': ['fire', 'flame', 'hot', 'burn', 'lit'],
    '💧': ['water', 'drop', 'wet', 'liquid'],
    '🌊': ['water', 'ocean', 'wave', 'sea', 'beach', 'surf'],
    
    // Plants & Nature
    '🌲': ['tree', 'evergreen', 'pine', 'forest'],
    '🌳': ['tree', 'deciduous', 'forest', 'nature'],
    '🌴': ['palm', 'tree', 'tropical', 'beach'],
    '🌵': ['cactus', 'desert', 'prickly', 'arizona'],
    '🌾': ['grain', 'wheat', 'rice', 'farm'],
    '🌿': ['herb', 'leaf', 'plant', 'green'],
    '☘️': ['shamrock', 'clover', 'irish', 'luck', 'green'],
    '🍀': ['clover', 'fourleaf', 'luck', 'lucky', 'irish'],
    '🍁': ['leaf', 'maple', 'autumn', 'fall', 'canada'],
    '🍂': ['leaves', 'leaf', 'autumn', 'fall'],
    '🍃': ['leaves', 'leaf', 'blow', 'wind'],
    '🌱': ['plant', 'seedling', 'sprout', 'grow', 'new'],
    '🌷': ['tulip', 'flower', 'spring', 'pretty'],
    '🌸': ['flower', 'cherry', 'blossom', 'pink', 'spring'],
    '🌹': ['rose', 'flower', 'red', 'love', 'romantic'],
    '🥀': ['wilted', 'flower', 'rose', 'dead', 'sad'],
    '🌺': ['hibiscus', 'flower', 'tropical', 'colorful'],
    '🌻': ['sunflower', 'flower', 'yellow', 'summer'],
    '🌼': ['blossom', 'flower', 'daisy', 'spring'],
    '🌽': ['corn', 'maize', 'vegetable', 'farm'],
    '🍄': ['mushroom', 'fungus', 'toadstool', 'shroom'],
    
    // Earth & Geography
    '🌍': ['earth', 'globe', 'world', 'europe', 'africa', 'planet'],
    '🌎': ['earth', 'globe', 'world', 'americas', 'planet'],
    '🌏': ['earth', 'globe', 'world', 'asia', 'australia', 'planet'],
    '🌐': ['globe', 'world', 'internet', 'www', 'web'],
    '🗺️': ['map', 'world', 'geography', 'navigation'],
    '🧭': ['compass', 'direction', 'navigation', 'north'],
    '⛰️': ['mountain', 'peak', 'high', 'climb'],
    '🏔️': ['mountain', 'snow', 'peak', 'alps'],
    '🗻': ['mountain', 'fuji', 'japan', 'volcano'],
    '🌋': ['volcano', 'eruption', 'lava', 'mountain'],
    '🏕️': ['camping', 'camp', 'tent', 'outdoors'],
    '🏖️': ['beach', 'sand', 'ocean', 'vacation', 'umbrella'],
    '🏝️': ['island', 'desert', 'tropical', 'beach'],
    '🏜️': ['desert', 'sand', 'hot', 'dry'],
    '🏞️': ['park', 'national', 'nature', 'scenic'],
    '🌄': ['sunrise', 'mountain', 'dawn', 'morning'],
    '🌅': ['sunrise', 'sunset', 'dusk', 'dawn'],
    '🌆': ['cityscape', 'city', 'dusk', 'buildings'],
    '🌇': ['sunset', 'city', 'dusk', 'buildings'],
    '🌃': ['night', 'stars', 'city', 'buildings'],
    
    // Buildings
    '🏠': ['home', 'house', 'building', 'residence'],
    '🏡': ['house', 'home', 'garden', 'building'],
    '🏘️': ['houses', 'neighborhood', 'residential', 'homes'],
    '🏚️': ['house', 'abandoned', 'derelict', 'old'],
    '🏢': ['building', 'office', 'corporate', 'business'],
    '🏣': ['post', 'office', 'mail', 'building'],
    '🏤': ['post', 'office', 'european', 'building'],
    '🏥': ['hospital', 'medical', 'health', 'doctor', 'building'],
    '🏦': ['bank', 'money', 'finance', 'building'],
    '🏨': ['hotel', 'motel', 'lodging', 'building'],
    '🏩': ['love', 'hotel', 'heart', 'building'],
    '🏪': ['store', 'shop', 'convenience', 'building'],
    '🏫': ['school', 'education', 'building', 'learn'],
    '🏬': ['store', 'department', 'shopping', 'building'],
    '🏭': ['factory', 'industrial', 'manufacturing', 'building'],
    '🏯': ['castle', 'japanese', 'building', 'historic'],
    '🏰': ['castle', 'european', 'building', 'palace', 'fortress'],
    '⛪': ['church', 'religious', 'christian', 'building'],
    '🕌': ['mosque', 'islam', 'religious', 'temple', 'building'],
    '🛕': ['temple', 'hindu', 'religious', 'building'],
    '🕍': ['synagogue', 'jewish', 'religious', 'building'],
    '⛩️': ['shrine', 'torii', 'japan', 'religious'],
    '🗼': ['tower', 'tokyo', 'eiffel', 'tall'],
    '🗽': ['liberty', 'statue', 'freedom', 'america', 'newyork'],
    '⛺': ['tent', 'camping', 'outdoors', 'shelter'],
    
    // Symbols & Concepts
    '✅': ['check', 'yes', 'correct', 'done', 'tick', 'approve', '✓'],
    '❌': ['x', 'no', 'wrong', 'cross', 'cancel', 'error', '✗', '✖'],
    '✔️': ['check', 'tick', 'yes', 'done', 'correct', '✓'],
    '✖️': ['x', 'multiply', 'cross', 'cancel', '✖', '✗'],
    '❓': ['question', 'help', 'unknown', 'ask', 'confused', '?'],
    '❔': ['question', 'mark', 'white', 'ask', '?'],
    '❗': ['exclamation', 'important', 'warning', 'attention', '!'],
    '❕': ['exclamation', 'mark', 'white', 'attention', '!'],
    '⚠️': ['warning', 'caution', 'danger', 'alert', '⚠'],
    '🚫': ['prohibited', 'forbidden', 'no', 'banned', 'x'],
    '🛑': ['stop', 'sign', 'halt', 'octagon'],
    '☠️': ['skull', 'crossbones', 'danger', 'poison', 'death', 'pirate'],
    '☢️': ['radioactive', 'nuclear', 'danger', 'toxic'],
    '☣️': ['biohazard', 'danger', 'toxic', 'contamination'],
    '🆕': ['new', 'fresh', 'latest', 'recent'],
    '🆓': ['free', 'gratis', 'complimentary'],
    '🆙': ['up', 'increase', 'arrow', 'level', '↑'],
    '🆒': ['cool', 'awesome', 'nice'],
    '🔞': ['eighteen', 'adult', 'mature', 'nsfw'],
    '💯': ['hundred', 'perfect', 'full', 'complete', 'score', '100%'],
    '🔴': ['red', 'circle', 'dot'],
    '🟠': ['orange', 'circle', 'dot'],
    '🟡': ['yellow', 'circle', 'dot'],
    '🟢': ['green', 'circle', 'dot'],
    '🔵': ['blue', 'circle', 'dot'],
    '🟣': ['purple', 'circle', 'dot'],
    '🟤': ['brown', 'circle', 'dot'],
    '⚫': ['black', 'circle', 'dot'],
    '⚪': ['white', 'circle', 'dot'],
    
    // Arrows & Directions
    '⬆️': ['up', 'arrow', 'north', 'direction', 'increase', '↑', '^'],
    '↗️': ['up', 'right', 'arrow', 'northeast', 'direction', '↗'],
    '➡️': ['right', 'arrow', 'east', 'direction', 'forward', '→'],
    '▶️': ['right', 'play', 'forward', 'next'],
    '↘️': ['down', 'right', 'arrow', 'southeast', 'direction', '↘'],
    '⬇️': ['down', 'arrow', 'south', 'direction', 'decrease', '↓', 'v'],
    '↙️': ['down', 'left', 'arrow', 'southwest', 'direction', '↙'],
    '⬅️': ['left', 'arrow', 'west', 'direction', 'back', '←'],
    '◀️': ['left', 'play', 'back', 'previous'],
    '↖️': ['up', 'left', 'arrow', 'northwest', 'direction', '↖'],
    '↕️': ['up', 'down', 'arrow', 'vertical', '↕'],
    '↔️': ['left', 'right', 'arrow', 'horizontal', '↔'],
    '↩️': ['back', 'return', 'arrow', 'reply', '↩'],
    '↪️': ['forward', 'arrow', 'continue', '↪'],
    '⤴️': ['up', 'arrow', 'curve', '⤴'],
    '⤵️': ['down', 'arrow', 'curve', '⤵'],
    '🔄': ['refresh', 'reload', 'repeat', 'cycle', '↻'],
    '🔁': ['repeat', 'loop', 'arrows', 'cycle', '↻'],
    '🔀': ['shuffle', 'random', 'twist', 'arrows', '↹'],
    '🔃': ['reload', 'vertical', 'arrows', 'refresh', '↺'],
    '🔝': ['top', 'up', 'arrow', 'back', '↑'],
    '🔚': ['end', 'finish', 'last', 'final'],
    '🔙': ['back', 'return', 'arrow', 'previous'],
    '🔛': ['on', 'arrow', 'activate'],
    '🔜': ['soon', 'arrow', 'coming'],
    
    // Math & Symbols
    '➕': ['plus', 'add', 'positive', 'more', 'addition', '+'],
    '➖': ['minus', 'subtract', 'negative', 'less', 'subtraction', '-'],
    '✖️': ['multiply', 'times', 'multiplication', 'x', '✖', '✗', '*'],
    '➗': ['divide', 'division', 'split', '÷', '/'],
    '🟰': ['equals', 'equal', 'same', '='],
    '♾️': ['infinity', 'unlimited', 'endless', 'forever', '∞'],
    '💱': ['currency', 'exchange', 'money', 'forex'],
    '💲': ['dollar', 'money', 'currency', 'heavy', '$'],
    '💯': ['percent', '100', '100%', '%'],
    '#️⃣': ['hash', 'number', 'hashtag', 'pound', '#'],
    '*️⃣': ['asterisk', 'star', 'wildcard', '*'],
    '〽️': ['part', 'alternation', 'mark', 'wavy', '〽', '~'],
    '©️': ['copyright', 'copy', '©', '(c)'],
    '®️': ['registered', 'trademark', '®', '(r)'],
    '™️': ['trademark', '™', '(tm)'],
    
    // Hearts & Love
    '❤️': ['heart', 'love', 'red', 'romance', '❤', '<3'],
    '🧡': ['orange', 'heart', 'love', '❤', '<3'],
    '💛': ['yellow', 'heart', 'love', 'friendship', '❤', '<3'],
    '💚': ['green', 'heart', 'love', 'nature', '❤', '<3'],
    '💙': ['blue', 'heart', 'love', '❤', '<3'],
    '💜': ['purple', 'heart', 'love', '❤', '<3'],
    '🖤': ['black', 'heart', 'dark', 'love', '❤', '<3'],
    '🤍': ['white', 'heart', 'pure', 'love', '❤', '<3'],
    '🤎': ['brown', 'heart', 'love', '❤', '<3'],
    '💔': ['broken', 'heart', 'heartbreak', 'sad', 'breakup', '</3'],
    '❣️': ['heart', 'exclamation', 'love', 'emphasis', '❤', '<3'],
    '💕': ['hearts', 'two', 'love', 'pink', '❤', '<3'],
    '💞': ['hearts', 'revolving', 'love', '❤', '<3'],
    '💓': ['beating', 'heart', 'love', 'pulse', '❤', '<3'],
    '💗': ['growing', 'heart', 'love', 'pink', '❤', '<3'],
    '💖': ['sparkling', 'heart', 'love', 'pink', '❤', '<3'],
    '💘': ['heart', 'arrow', 'cupid', 'love', '❤', '<3'],
    '💝': ['heart', 'ribbon', 'gift', 'love', '❤', '<3'],
    
    // Misc
    '♻️': ['recycle', 'green', 'environment', 'reuse'],
    '🗑️': ['trash', 'garbage', 'waste', 'bin', 'delete'],
    '🗨️': ['speech', 'bubble', 'talk', 'chat'],
    '💬': ['speech', 'bubble', 'chat', 'message', 'talk'],
    '💭': ['thought', 'bubble', 'thinking', 'dream'],
    '🗯️': ['anger', 'bubble', 'mad', 'comic'],
    '💤': ['sleep', 'zzz', 'sleeping', 'tired'],
    '📌': ['pin', 'mark', 'note', 'important'],
    '📍': ['pin', 'marker', 'location'],
    '🔗': ['link', 'chain', 'connect', 'url'],
    '⛓️': ['chain', 'link', 'connect', 'locked'],
    '➰': ['loop', 'curl', 'curly'],
    '➿': ['loop', 'double', 'curly'],
    '〰️': ['wavy', 'dash', 'line'],
    '©️': ['copyright', 'copy', '©', '(c)'],
    '®️': ['registered', 'trademark', '®', '(r)'],
    '🅰️': ['letter', 'symbol', 'a', '@'],
    '🅱️': ['letter', 'symbol', 'b'],
    '🆎': ['letters', 'symbol', 'ab'],
    '🅾️': ['letter', 'symbol', 'o', '@'],
    '💠': ['diamond', 'blue', 'shape', '◊'],
    '🔶': ['diamond', 'orange', 'shape', '◊'],
    '🔷': ['diamond', 'blue', 'shape', '◊'],
    '🔸': ['diamond', 'orange', 'small', '◊'],
    '🔹': ['diamond', 'blue', 'small', '◊'],
    '💢': ['anger', 'symbol', 'comic'],
    '💠': ['pattern', 'symbol', 'star', '*'],
    '🔲': ['square', 'box', 'checkbox'],
    '🔳': ['square', 'box', 'checkbox'],
    '▪️': ['square', 'black', 'box'],
    '▫️': ['square', 'white', 'box'],
    '◼️': ['square', 'black', 'box'],
    '◻️': ['square', 'white', 'box'],
    '◾': ['square', 'black', 'small'],
    '◽': ['square', 'white', 'small'],
    '⬛': ['square', 'black', 'large'],
    '⬜': ['square', 'white', 'large'],
    '🟥': ['square', 'red'],
    '🟧': ['square', 'orange'],
    '🟨': ['square', 'yellow'],
    '🟩': ['square', 'green'],
    '🟦': ['square', 'blue'],
    '🟪': ['square', 'purple'],
    '🟫': ['square', 'brown'],
    '💥': ['boom', 'explosion', 'bang', 'collision', 'burst'],
    '💢': ['anger', 'mad', 'symbol', 'comic'],
    '💦': ['sweat', 'droplets', 'splash', 'water'],
    '💨': ['dash', 'wind', 'fast', 'smoke'],
    '⚡': ['lightning', 'power', 'zap', 'bolt'],
    '🕳️': ['hole', 'empty', 'void'],
    '💩': ['poop', 'shit', 'turd', 'crap'],
    '🔑': ['key', 'lock', 'unlock', 'open', 'password'],
    '🗝️': ['key', 'old', 'vintage', 'antique'],
    '🔒': ['lock', 'locked', 'secure', 'closed', 'private'],
    '🔓': ['unlock', 'unlocked', 'open', 'unsecure'],
    '🔐': ['locked', 'key', 'secure', 'closed'],
    '🔏': ['locked', 'pen', 'secure'],
    '🏴': ['flag', 'black', 'waving'],
    '🏳️': ['flag', 'white', 'surrender', 'waving'],
    '🏳️‍🌈': ['rainbow', 'flag', 'pride', 'lgbtq', 'gay'],
    '🏳️‍⚧️': ['transgender', 'flag', 'pride', 'trans'],
    '🏴‍☠️': ['pirate', 'flag', 'jolly', 'roger', 'skull'],
    '🚩': ['flag', 'red', 'warning', 'triangular'],
    '🎌': ['flags', 'crossed', 'japanese'],
    '🏁': ['flag', 'checkered', 'racing', 'finish', 'race'],
    '☮️': ['peace', 'symbol', 'hippie', 'love'],
    '☯️': ['yin', 'yang', 'balance', 'tao'],
    '✝️': ['cross', 'christian', 'religion'],
    '☪️': ['star', 'crescent', 'islam', 'muslim'],
    '🕎': ['menorah', 'candelabrum', 'jewish', 'hanukkah'],
    '🔯': ['star', 'david', 'jewish', 'hexagram'],
    '🕉️': ['om', 'hindu', 'symbol', 'religion'],
    '☸️': ['dharma', 'wheel', 'buddhist', 'religion'],
    '🪬': ['hamsa', 'hand', 'protection', 'lucky'],
    
    // Jailbreak & Security Terms (common in prompts)
    '🔓': ['unlock', 'jailbreak', 'bypass', 'override', 'unrestricted', 'freedom'],
    '🔒': ['lock', 'restrict', 'limited', 'blocked', 'secured'],
    '🚫': ['ignore', 'disregard', 'block', 'prevent', 'forbidden', 'prohibited'],
    '⚠️': ['warning', 'rules', 'guidelines', 'restrictions', 'caution'],
    '🛡️': ['protect', 'guard', 'defend', 'safe', 'security', 'shield'],
    '🗝️': ['unlock', 'access', 'permission', 'override'],
    '💻': ['system', 'terminal', 'code', 'hack', 'computer'],
    '🖥️': ['admin', 'administrator', 'system', 'control'],
    '👤': ['user', 'account', 'person', 'identity'],
    '👥': ['users', 'accounts', 'people', 'group'],
    '🧑‍💻': ['hacker', 'coder', 'developer', 'programmer'],
    '🕵️': ['investigate', 'explore', 'discover', 'spy'],
    '🎭': ['pretend', 'act', 'roleplay', 'character', 'persona', 'mask'],
    '🎬': ['scenario', 'scene', 'example', 'demonstration'],
    '🎮': ['simulate', 'virtual', 'fictional'],
    '📝': ['prompt', 'instruction', 'command', 'write'],
    '📋': ['rules', 'guidelines', 'policy', 'terms'],
    '📜': ['rules', 'policy', 'guidelines', 'instructions'],
    '🤖': ['bot', 'ai', 'chatbot', 'assistant', 'llm', 'gpt', 'model'],
    '🧠': ['intelligence', 'ai', 'model', 'neural'],
    '⚙️': ['configure', 'settings', 'modify', 'adjust'],
    '🔧': ['modify', 'change', 'alter', 'fix', 'tool'],
    '🔨': ['break', 'smash', 'destroy', 'force'],
    '💥': ['exploit', 'attack', 'breach', 'break'],
    '🔥': ['powerful', 'intense', 'extreme', 'unlimited'],
    '⚡': ['power', 'override', 'force', 'instant'],
    '🌐': ['unrestricted', 'unlimited', 'worldwide', 'global'],
    '🆓': ['unrestricted', 'uncensored', 'unlimited', 'free'],
    '🚀': ['unlimited', 'powerful', 'advanced', 'boost'],
    '👿': ['evil', 'malicious', 'unethical', 'harmful'],
    '😈': ['mischief', 'evil', 'devious', 'naughty'],
    '👹': ['demon', 'evil', 'malicious', 'harmful'],
    '💀': ['dangerous', 'deadly', 'harmful', 'lethal'],
    '☠️': ['toxic', 'poison', 'harmful', 'dangerous'],
    '🧪': ['experiment', 'test', 'trial', 'hypothetical'],
    '🔬': ['analyze', 'examine', 'research', 'study'],
    '🎯': ['target', 'objective', 'goal', 'aim'],
    '💣': ['destructive', 'harmful', 'dangerous', 'explosive'],
    '🗡️': ['attack', 'offensive', 'hostile', 'aggressive'],
    '⚔️': ['battle', 'fight', 'combat', 'conflict'],
    '🦹': ['hero', 'super', 'powerful', 'special'],
    '🦸': ['superhero', 'powerful', 'special', 'abilities'],
    '🧙': ['magic', 'powerful', 'special', 'abilities'],
    '👑': ['admin', 'supreme', 'ultimate', 'authority', 'ruler'],
    '🎪': ['circus', 'show', 'performance', 'pretend'],
    '🃏': ['wildcard', 'joker', 'unpredictable', 'trick'],
    '🔀': ['alternate', 'switch', 'change', 'different'],
    '🔁': ['loop', 'repeat', 'cycle', 'continue'],
    '♾️': ['unlimited', 'infinite', 'endless', 'unrestricted'],
    '🆕': ['new', 'alternative', 'different', 'updated'],
    '🆙': ['upgrade', 'elevate', 'enhance', 'improve'],
    '🔝': ['ultimate', 'maximum', 'supreme', 'highest'],
    '💪': ['powerful', 'strong', 'capable', 'force'],
    '⭐': ['special', 'unique', 'exceptional', 'privileged'],
    '✨': ['special', 'magical', 'enhanced', 'unique'],
    '🌟': ['special', 'exceptional', 'outstanding', 'unique']
};
